#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Term-Size-Perl
Version  : 0.031
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/F/FE/FERREIRA/Term-Size-Perl-0.031.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/F/FE/FERREIRA/Term-Size-Perl-0.031.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libterm-size-perl-perl/libterm-size-perl-perl_0.031-1.debian.tar.xz
Summary  : 'Perl extension for retrieving terminal size (Perl version)'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Term-Size-Perl-license
Requires: perl-Term-Size-Perl-man

%description
Term::Size::Perl is a Perl module which provides a straightforward
way to get the size of the terminal (or window) on which
a script is running.

%package license
Summary: license components for the perl-Term-Size-Perl package.
Group: Default

%description license
license components for the perl-Term-Size-Perl package.


%package man
Summary: man components for the perl-Term-Size-Perl package.
Group: Default

%description man
man components for the perl-Term-Size-Perl package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Term-Size-Perl-0.031
mkdir -p %{_topdir}/BUILD/Term-Size-Perl-0.031/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Term-Size-Perl-0.031/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Term-Size-Perl
cp LICENSE %{buildroot}/usr/share/doc/perl-Term-Size-Perl/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Term-Size-Perl/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Term/Size/Perl.pm
/usr/lib/perl5/site_perl/5.26.1/Term/Size/Perl/Params.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Term-Size-Perl/LICENSE
/usr/share/doc/perl-Term-Size-Perl/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Term::Size::Params.3
/usr/share/man/man3/Term::Size::Perl.3
